### ISSUE TITLE
ws connection timeout

### ISSUE THREAD

**Issue by selimanac** [gamestdio/colyseus-defold#7]
Is there a timeout when ws connection fails? Can we set it? (I couldn't find it on documentation or on forum)

**Comment by endel** [comment]
Hey @selimanac, this feature has been added into `defold-websocket` by @britzl last month (https://github.com/britzl/defold-websocket/commit/8ca46799ce51784b9cfa85bd7d3ef67efe741181)

I've just exposed this option this way on `colyseus-defold`:

```
local ColyseusConnection = require "colyseus.connection"
ColyseusConnection.config = { connect_timeout = 10 }
```

Hope this helps! Cheers!
