### ISSUE TITLE
Unable to get client.sessionId

### ISSUE THREAD

**Issue by holyxiaoxin** [gamestdio/colyseus-defold#9]
I am able to retrieve client.id but not able to get client.sessionId. Is this deliberate since there is no need for client.sessionId?

**Comment by endel** [comment]
Hi @holyxiaoxin, the `sessionId` attribute is attached to the `room` instance.

```lua
local room = client:join("room_name")

room:on("join", function() 
  print(client.id) -- id of the client
  print(room.sessionId) -- id of the session
end)
```

Cheers!

**Comment by holyxiaoxin** [comment]
My bad, they clarified this in the next line. Thanks!

http://colyseus.io/docs/api-client/#sessionid-string
